






DROP DATABASE IF EXISTS dachuang;
CREATE DATABASE dachuang CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'dachuang'@'%' IDENTIFIED BY 'Dachuang123!';
GRANT ALL PRIVILEGES ON dachuang.* TO 'dachuang'@'%';
FLUSH PRIVILEGES;

